// Generated by gencpp from file moscpp/GetLoggers.msg
// DO NOT EDIT!


#ifndef MOSCPP_MESSAGE_GETLOGGERS_H
#define MOSCPP_MESSAGE_GETLOGGERS_H

#include "mos_service_traits.h"


#include "moscpp/GetLoggersRequest.h"
#include "moscpp/GetLoggersResponse.h"


namespace moscpp
{

struct GetLoggers
{

typedef GetLoggersRequest Request;
typedef GetLoggersResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetLoggers
} // namespace moscpp


namespace mos
{
namespace service_traits
{


template<>
struct MD5Sum< ::moscpp::GetLoggers > {
  static const char* value()
  {
    return "32e97e85527d4678a8f9279894bb64b0";
  }

  static const char* value(const ::moscpp::GetLoggers&) { return value(); }
};

template<>
struct DataType< ::moscpp::GetLoggers > {
  static const char* value()
  {
    return "moscpp/GetLoggers";
  }

  static const char* value(const ::moscpp::GetLoggers&) { return value(); }
};


// service_traits::MD5Sum< ::moscpp::GetLoggersRequest> should match
// service_traits::MD5Sum< ::moscpp::GetLoggers >
template<>
struct MD5Sum< ::moscpp::GetLoggersRequest>
{
  static const char* value()
  {
    return MD5Sum< ::moscpp::GetLoggers >::value();
  }
  static const char* value(const ::moscpp::GetLoggersRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::moscpp::GetLoggersRequest> should match
// service_traits::DataType< ::moscpp::GetLoggers >
template<>
struct DataType< ::moscpp::GetLoggersRequest>
{
  static const char* value()
  {
    return DataType< ::moscpp::GetLoggers >::value();
  }
  static const char* value(const ::moscpp::GetLoggersRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::moscpp::GetLoggersResponse> should match
// service_traits::MD5Sum< ::moscpp::GetLoggers >
template<>
struct MD5Sum< ::moscpp::GetLoggersResponse>
{
  static const char* value()
  {
    return MD5Sum< ::moscpp::GetLoggers >::value();
  }
  static const char* value(const ::moscpp::GetLoggersResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::moscpp::GetLoggersResponse> should match
// service_traits::DataType< ::moscpp::GetLoggers >
template<>
struct DataType< ::moscpp::GetLoggersResponse>
{
  static const char* value()
  {
    return DataType< ::moscpp::GetLoggers >::value();
  }
  static const char* value(const ::moscpp::GetLoggersResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace mos

#endif // MOSCPP_MESSAGE_GETLOGGERS_H
