// Generated by gencpp from file moscpp/GetLoggersRequest.msg
// DO NOT EDIT!


#ifndef MOSCPP_MESSAGE_GETLOGGERSREQUEST_H
#define MOSCPP_MESSAGE_GETLOGGERSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include "mos_types.h"
#include "mos_serialization.h"
#include "mos_builtin_message_traits.h"
#include "mos_message_operations.h"


namespace moscpp
{
template <class ContainerAllocator>
struct GetLoggersRequest_
{
  typedef GetLoggersRequest_<ContainerAllocator> Type;

  GetLoggersRequest_()
    {
    }
  GetLoggersRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::moscpp::GetLoggersRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::moscpp::GetLoggersRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetLoggersRequest_

typedef ::moscpp::GetLoggersRequest_<std::allocator<void> > GetLoggersRequest;

typedef boost::shared_ptr< ::moscpp::GetLoggersRequest > GetLoggersRequestPtr;
typedef boost::shared_ptr< ::moscpp::GetLoggersRequest const> GetLoggersRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::moscpp::GetLoggersRequest_<ContainerAllocator> & v)
{
mos::message_operations::Printer< ::moscpp::GetLoggersRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace moscpp

namespace mos
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::moscpp::GetLoggersRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::moscpp::GetLoggersRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::moscpp::GetLoggersRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::moscpp::GetLoggersRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moscpp::GetLoggersRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moscpp::GetLoggersRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::moscpp::GetLoggersRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::moscpp::GetLoggersRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::moscpp::GetLoggersRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "moscpp/GetLoggersRequest";
  }

  static const char* value(const ::moscpp::GetLoggersRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::moscpp::GetLoggersRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::moscpp::GetLoggersRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace mos

namespace mos
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::moscpp::GetLoggersRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    MOS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetLoggersRequest_

} // namespace serialization
} // namespace mos

namespace mos
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::moscpp::GetLoggersRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::moscpp::GetLoggersRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace mos

#endif // MOSCPP_MESSAGE_GETLOGGERSREQUEST_H
