// Generated by gencpp from file moscpp/Logger.msg
// DO NOT EDIT!


#ifndef MOSCPP_MESSAGE_LOGGER_H
#define MOSCPP_MESSAGE_LOGGER_H


#include <string>
#include <vector>
#include <map>

#include "mos_types.h"
#include "mos_serialization.h"
#include "mos_builtin_message_traits.h"
#include "mos_message_operations.h"


namespace moscpp
{
template <class ContainerAllocator>
struct Logger_
{
  typedef Logger_<ContainerAllocator> Type;

  Logger_()
    : name()
    , level()  {
    }
  Logger_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , level(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _level_type;
  _level_type level;





  typedef boost::shared_ptr< ::moscpp::Logger_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::moscpp::Logger_<ContainerAllocator> const> ConstPtr;

}; // struct Logger_

typedef ::moscpp::Logger_<std::allocator<void> > Logger;

typedef boost::shared_ptr< ::moscpp::Logger > LoggerPtr;
typedef boost::shared_ptr< ::moscpp::Logger const> LoggerConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::moscpp::Logger_<ContainerAllocator> & v)
{
mos::message_operations::Printer< ::moscpp::Logger_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::moscpp::Logger_<ContainerAllocator1> & lhs, const ::moscpp::Logger_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.level == rhs.level;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::moscpp::Logger_<ContainerAllocator1> & lhs, const ::moscpp::Logger_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace moscpp

namespace mos
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::moscpp::Logger_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::moscpp::Logger_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::moscpp::Logger_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::moscpp::Logger_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moscpp::Logger_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moscpp::Logger_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::moscpp::Logger_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a6069a2ff40db7bd32143dd66e1f408e";
  }

  static const char* value(const ::moscpp::Logger_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa6069a2ff40db7bdULL;
  static const uint64_t static_value2 = 0x32143dd66e1f408eULL;
};

template<class ContainerAllocator>
struct DataType< ::moscpp::Logger_<ContainerAllocator> >
{
  static const char* value()
  {
    return "moscpp/Logger";
  }

  static const char* value(const ::moscpp::Logger_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::moscpp::Logger_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"string level\n"
;
  }

  static const char* value(const ::moscpp::Logger_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace mos

namespace mos
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::moscpp::Logger_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.level);
    }

    MOS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Logger_

} // namespace serialization
} // namespace mos

namespace mos
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::moscpp::Logger_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::moscpp::Logger_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "level: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.level);
  }
};

} // namespace message_operations
} // namespace mos

#endif // MOSCPP_MESSAGE_LOGGER_H
