// Generated by gencpp from file moscpp/SetLoggerLevel.msg
// DO NOT EDIT!


#ifndef MOSCPP_MESSAGE_SETLOGGERLEVEL_H
#define MOSCPP_MESSAGE_SETLOGGERLEVEL_H

#include "mos_service_traits.h"


#include "moscpp/SetLoggerLevelRequest.h"
#include "moscpp/SetLoggerLevelResponse.h"


namespace moscpp
{

struct SetLoggerLevel
{

typedef SetLoggerLevelRequest Request;
typedef SetLoggerLevelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetLoggerLevel
} // namespace moscpp


namespace mos
{
namespace service_traits
{


template<>
struct MD5Sum< ::moscpp::SetLoggerLevel > {
  static const char* value()
  {
    return "51da076440d78ca1684d36c868df61ea";
  }

  static const char* value(const ::moscpp::SetLoggerLevel&) { return value(); }
};

template<>
struct DataType< ::moscpp::SetLoggerLevel > {
  static const char* value()
  {
    return "moscpp/SetLoggerLevel";
  }

  static const char* value(const ::moscpp::SetLoggerLevel&) { return value(); }
};


// service_traits::MD5Sum< ::moscpp::SetLoggerLevelRequest> should match
// service_traits::MD5Sum< ::moscpp::SetLoggerLevel >
template<>
struct MD5Sum< ::moscpp::SetLoggerLevelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::moscpp::SetLoggerLevel >::value();
  }
  static const char* value(const ::moscpp::SetLoggerLevelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::moscpp::SetLoggerLevelRequest> should match
// service_traits::DataType< ::moscpp::SetLoggerLevel >
template<>
struct DataType< ::moscpp::SetLoggerLevelRequest>
{
  static const char* value()
  {
    return DataType< ::moscpp::SetLoggerLevel >::value();
  }
  static const char* value(const ::moscpp::SetLoggerLevelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::moscpp::SetLoggerLevelResponse> should match
// service_traits::MD5Sum< ::moscpp::SetLoggerLevel >
template<>
struct MD5Sum< ::moscpp::SetLoggerLevelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::moscpp::SetLoggerLevel >::value();
  }
  static const char* value(const ::moscpp::SetLoggerLevelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::moscpp::SetLoggerLevelResponse> should match
// service_traits::DataType< ::moscpp::SetLoggerLevel >
template<>
struct DataType< ::moscpp::SetLoggerLevelResponse>
{
  static const char* value()
  {
    return DataType< ::moscpp::SetLoggerLevel >::value();
  }
  static const char* value(const ::moscpp::SetLoggerLevelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace mos

#endif // MOSCPP_MESSAGE_SETLOGGERLEVEL_H
