// !!!!!!!!!!!!!!!!!!!!!!! This is a generated file, do not edit manually

/*
 * Copyright (c) 2008, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of Willow Garage, Inc. nor the names of its
 *       contributors may be used to endorse or promote products derived from
 *       this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#if (MOSCONSOLE_MIN_SEVERITY > MOSCONSOLE_SEVERITY_DEBUG)
#define MOS_DEBUG(...)
#define MOS_DEBUG_STREAM(args)
#define MOS_DEBUG_NAMED(name, ...)
#define MOS_DEBUG_STREAM_NAMED(name, args)
#define MOS_DEBUG_COND(cond, ...)
#define MOS_DEBUG_STREAM_COND(cond, args)
#define MOS_DEBUG_COND_NAMED(cond, name, ...)
#define MOS_DEBUG_STREAM_COND_NAMED(cond, name, args)
#define MOS_DEBUG_ONCE(...)
#define MOS_DEBUG_STREAM_ONCE(args)
#define MOS_DEBUG_ONCE_NAMED(name, ...)
#define MOS_DEBUG_STREAM_ONCE_NAMED(name, args)
#define MOS_DEBUG_THROTTLE(period, ...)
#define MOS_DEBUG_STREAM_THROTTLE(period, args)
#define MOS_DEBUG_THROTTLE_NAMED(period, name, ...)
#define MOS_DEBUG_STREAM_THROTTLE_NAMED(period, name, args)
#define MOS_DEBUG_DELAYED_THROTTLE(period, ...)
#define MOS_DEBUG_STREAM_DELAYED_THROTTLE(period, args)
#define MOS_DEBUG_DELAYED_THROTTLE_NAMED(period, name, ...)
#define MOS_DEBUG_STREAM_DELAYED_THROTTLE_NAMED(period, name, args)
#define MOS_DEBUG_FILTER(filter, ...)
#define MOS_DEBUG_STREAM_FILTER(filter, args)
#define MOS_DEBUG_FILTER_NAMED(filter, name, ...)
#define MOS_DEBUG_STREAM_FILTER_NAMED(filter, name, args)
#else
#define MOS_DEBUG(...) MOS_LOG(::mos::console::levels::Debug, MOSCONSOLE_DEFAULT_NAME, __VA_ARGS__)
#define MOS_DEBUG_STREAM(args) MOS_LOG_STREAM(::mos::console::levels::Debug, MOSCONSOLE_DEFAULT_NAME, args)
#define MOS_DEBUG_NAMED(name, ...) MOS_LOG(::mos::console::levels::Debug, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, __VA_ARGS__)
#define MOS_DEBUG_STREAM_NAMED(name, args) MOS_LOG_STREAM(::mos::console::levels::Debug, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, args)
#define MOS_DEBUG_COND(cond, ...) MOS_LOG_COND(cond, ::mos::console::levels::Debug, MOSCONSOLE_DEFAULT_NAME, __VA_ARGS__)
#define MOS_DEBUG_STREAM_COND(cond, args) MOS_LOG_STREAM_COND(cond, ::mos::console::levels::Debug, MOSCONSOLE_DEFAULT_NAME, args)
#define MOS_DEBUG_COND_NAMED(cond, name, ...) MOS_LOG_COND(cond, ::mos::console::levels::Debug, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, __VA_ARGS__)
#define MOS_DEBUG_STREAM_COND_NAMED(cond, name, args) MOS_LOG_STREAM_COND(cond, ::mos::console::levels::Debug, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, args)
#define MOS_DEBUG_ONCE(...) MOS_LOG_ONCE(::mos::console::levels::Debug, MOSCONSOLE_DEFAULT_NAME, __VA_ARGS__)
#define MOS_DEBUG_STREAM_ONCE(args) MOS_LOG_STREAM_ONCE(::mos::console::levels::Debug, MOSCONSOLE_DEFAULT_NAME, args)
#define MOS_DEBUG_ONCE_NAMED(name, ...) MOS_LOG_ONCE(::mos::console::levels::Debug, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, __VA_ARGS__)
#define MOS_DEBUG_STREAM_ONCE_NAMED(name, args) MOS_LOG_STREAM_ONCE(::mos::console::levels::Debug, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, args)
#define MOS_DEBUG_THROTTLE(period, ...) MOS_LOG_THROTTLE(period, ::mos::console::levels::Debug, MOSCONSOLE_DEFAULT_NAME, __VA_ARGS__)
#define MOS_DEBUG_STREAM_THROTTLE(period, args) MOS_LOG_STREAM_THROTTLE(period, ::mos::console::levels::Debug, MOSCONSOLE_DEFAULT_NAME, args)
#define MOS_DEBUG_THROTTLE_NAMED(period, name, ...) MOS_LOG_THROTTLE(period, ::mos::console::levels::Debug, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, __VA_ARGS__)
#define MOS_DEBUG_STREAM_THROTTLE_NAMED(period, name, args) MOS_LOG_STREAM_THROTTLE(period, ::mos::console::levels::Debug, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, args)
#define MOS_DEBUG_DELAYED_THROTTLE(period, ...) MOS_LOG_DELAYED_THROTTLE(period, ::mos::console::levels::Debug, MOSCONSOLE_DEFAULT_NAME, __VA_ARGS__)
#define MOS_DEBUG_STREAM_DELAYED_THROTTLE(period, args) MOS_LOG_STREAM_DELAYED_THROTTLE(period, ::mos::console::levels::Debug, MOSCONSOLE_DEFAULT_NAME, args)
#define MOS_DEBUG_DELAYED_THROTTLE_NAMED(period, name, ...) MOS_LOG_DELAYED_THROTTLE(period, ::mos::console::levels::Debug, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, __VA_ARGS__)
#define MOS_DEBUG_STREAM_DELAYED_THROTTLE_NAMED(period, name, args) MOS_LOG_STREAM_DELAYED_THROTTLE(period, ::mos::console::levels::Debug, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, args)
#define MOS_DEBUG_FILTER(filter, ...) MOS_LOG_FILTER(filter, ::mos::console::levels::Debug, MOSCONSOLE_DEFAULT_NAME, __VA_ARGS__)
#define MOS_DEBUG_STREAM_FILTER(filter, args) MOS_LOG_STREAM_FILTER(filter, ::mos::console::levels::Debug, MOSCONSOLE_DEFAULT_NAME, args)
#define MOS_DEBUG_FILTER_NAMED(filter, name, ...) MOS_LOG_FILTER(filter, ::mos::console::levels::Debug, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, __VA_ARGS__)
#define MOS_DEBUG_STREAM_FILTER_NAMED(filter, name, args) MOS_LOG_STREAM_FILTER(filter, ::mos::console::levels::Debug, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, args)
#endif

#if (MOSCONSOLE_MIN_SEVERITY > MOSCONSOLE_SEVERITY_INFO)
#define MOS_INFO(...)
#define MOS_INFO_STREAM(args)
#define MOS_INFO_NAMED(name, ...)
#define MOS_INFO_STREAM_NAMED(name, args)
#define MOS_INFO_COND(cond, ...)
#define MOS_INFO_STREAM_COND(cond, args)
#define MOS_INFO_COND_NAMED(cond, name, ...)
#define MOS_INFO_STREAM_COND_NAMED(cond, name, args)
#define MOS_INFO_ONCE(...)
#define MOS_INFO_STREAM_ONCE(args)
#define MOS_INFO_ONCE_NAMED(name, ...)
#define MOS_INFO_STREAM_ONCE_NAMED(name, args)
#define MOS_INFO_THROTTLE(period, ...)
#define MOS_INFO_STREAM_THROTTLE(period, args)
#define MOS_INFO_THROTTLE_NAMED(period, name, ...)
#define MOS_INFO_STREAM_THROTTLE_NAMED(period, name, args)
#define MOS_INFO_DELAYED_THROTTLE(period, ...)
#define MOS_INFO_STREAM_DELAYED_THROTTLE(period, args)
#define MOS_INFO_DELAYED_THROTTLE_NAMED(period, name, ...)
#define MOS_INFO_STREAM_DELAYED_THROTTLE_NAMED(period, name, args)
#define MOS_INFO_FILTER(filter, ...)
#define MOS_INFO_STREAM_FILTER(filter, args)
#define MOS_INFO_FILTER_NAMED(filter, name, ...)
#define MOS_INFO_STREAM_FILTER_NAMED(filter, name, args)
#else
#define MOS_INFO(...) MOS_LOG(::mos::console::levels::Info, MOSCONSOLE_DEFAULT_NAME, __VA_ARGS__)
#define MOS_INFO_STREAM(args) MOS_LOG_STREAM(::mos::console::levels::Info, MOSCONSOLE_DEFAULT_NAME, args)
#define MOS_INFO_NAMED(name, ...) MOS_LOG(::mos::console::levels::Info, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, __VA_ARGS__)
#define MOS_INFO_STREAM_NAMED(name, args) MOS_LOG_STREAM(::mos::console::levels::Info, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, args)
#define MOS_INFO_COND(cond, ...) MOS_LOG_COND(cond, ::mos::console::levels::Info, MOSCONSOLE_DEFAULT_NAME, __VA_ARGS__)
#define MOS_INFO_STREAM_COND(cond, args) MOS_LOG_STREAM_COND(cond, ::mos::console::levels::Info, MOSCONSOLE_DEFAULT_NAME, args)
#define MOS_INFO_COND_NAMED(cond, name, ...) MOS_LOG_COND(cond, ::mos::console::levels::Info, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, __VA_ARGS__)
#define MOS_INFO_STREAM_COND_NAMED(cond, name, args) MOS_LOG_STREAM_COND(cond, ::mos::console::levels::Info, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, args)
#define MOS_INFO_ONCE(...) MOS_LOG_ONCE(::mos::console::levels::Info, MOSCONSOLE_DEFAULT_NAME, __VA_ARGS__)
#define MOS_INFO_STREAM_ONCE(args) MOS_LOG_STREAM_ONCE(::mos::console::levels::Info, MOSCONSOLE_DEFAULT_NAME, args)
#define MOS_INFO_ONCE_NAMED(name, ...) MOS_LOG_ONCE(::mos::console::levels::Info, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, __VA_ARGS__)
#define MOS_INFO_STREAM_ONCE_NAMED(name, args) MOS_LOG_STREAM_ONCE(::mos::console::levels::Info, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, args)
#define MOS_INFO_THROTTLE(period, ...) MOS_LOG_THROTTLE(period, ::mos::console::levels::Info, MOSCONSOLE_DEFAULT_NAME, __VA_ARGS__)
#define MOS_INFO_STREAM_THROTTLE(period, args) MOS_LOG_STREAM_THROTTLE(period, ::mos::console::levels::Info, MOSCONSOLE_DEFAULT_NAME, args)
#define MOS_INFO_THROTTLE_NAMED(period, name, ...) MOS_LOG_THROTTLE(period, ::mos::console::levels::Info, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, __VA_ARGS__)
#define MOS_INFO_STREAM_THROTTLE_NAMED(period, name, args) MOS_LOG_STREAM_THROTTLE(period, ::mos::console::levels::Info, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, args)
#define MOS_INFO_DELAYED_THROTTLE(period, ...) MOS_LOG_DELAYED_THROTTLE(period, ::mos::console::levels::Info, MOSCONSOLE_DEFAULT_NAME, __VA_ARGS__)
#define MOS_INFO_STREAM_DELAYED_THROTTLE(period, args) MOS_LOG_STREAM_DELAYED_THROTTLE(period, ::mos::console::levels::Info, MOSCONSOLE_DEFAULT_NAME, args)
#define MOS_INFO_DELAYED_THROTTLE_NAMED(period, name, ...) MOS_LOG_DELAYED_THROTTLE(period, ::mos::console::levels::Info, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, __VA_ARGS__)
#define MOS_INFO_STREAM_DELAYED_THROTTLE_NAMED(period, name, args) MOS_LOG_STREAM_DELAYED_THROTTLE(period, ::mos::console::levels::Info, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, args)
#define MOS_INFO_FILTER(filter, ...) MOS_LOG_FILTER(filter, ::mos::console::levels::Info, MOSCONSOLE_DEFAULT_NAME, __VA_ARGS__)
#define MOS_INFO_STREAM_FILTER(filter, args) MOS_LOG_STREAM_FILTER(filter, ::mos::console::levels::Info, MOSCONSOLE_DEFAULT_NAME, args)
#define MOS_INFO_FILTER_NAMED(filter, name, ...) MOS_LOG_FILTER(filter, ::mos::console::levels::Info, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, __VA_ARGS__)
#define MOS_INFO_STREAM_FILTER_NAMED(filter, name, args) MOS_LOG_STREAM_FILTER(filter, ::mos::console::levels::Info, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, args)
#endif

#if (MOSCONSOLE_MIN_SEVERITY > MOSCONSOLE_SEVERITY_WARN)
#define MOS_WARN(...)
#define MOS_WARN_STREAM(args)
#define MOS_WARN_NAMED(name, ...)
#define MOS_WARN_STREAM_NAMED(name, args)
#define MOS_WARN_COND(cond, ...)
#define MOS_WARN_STREAM_COND(cond, args)
#define MOS_WARN_COND_NAMED(cond, name, ...)
#define MOS_WARN_STREAM_COND_NAMED(cond, name, args)
#define MOS_WARN_ONCE(...)
#define MOS_WARN_STREAM_ONCE(args)
#define MOS_WARN_ONCE_NAMED(name, ...)
#define MOS_WARN_STREAM_ONCE_NAMED(name, args)
#define MOS_WARN_THROTTLE(period, ...)
#define MOS_WARN_STREAM_THROTTLE(period, args)
#define MOS_WARN_THROTTLE_NAMED(period, name, ...)
#define MOS_WARN_STREAM_THROTTLE_NAMED(period, name, args)
#define MOS_WARN_DELAYED_THROTTLE(period, ...)
#define MOS_WARN_STREAM_DELAYED_THROTTLE(period, args)
#define MOS_WARN_DELAYED_THROTTLE_NAMED(period, name, ...)
#define MOS_WARN_STREAM_DELAYED_THROTTLE_NAMED(period, name, args)
#define MOS_WARN_FILTER(filter, ...)
#define MOS_WARN_STREAM_FILTER(filter, args)
#define MOS_WARN_FILTER_NAMED(filter, name, ...)
#define MOS_WARN_STREAM_FILTER_NAMED(filter, name, args)
#else
#define MOS_WARN(...) MOS_LOG(::mos::console::levels::Warn, MOSCONSOLE_DEFAULT_NAME, __VA_ARGS__)
#define MOS_WARN_STREAM(args) MOS_LOG_STREAM(::mos::console::levels::Warn, MOSCONSOLE_DEFAULT_NAME, args)
#define MOS_WARN_NAMED(name, ...) MOS_LOG(::mos::console::levels::Warn, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, __VA_ARGS__)
#define MOS_WARN_STREAM_NAMED(name, args) MOS_LOG_STREAM(::mos::console::levels::Warn, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, args)
#define MOS_WARN_COND(cond, ...) MOS_LOG_COND(cond, ::mos::console::levels::Warn, MOSCONSOLE_DEFAULT_NAME, __VA_ARGS__)
#define MOS_WARN_STREAM_COND(cond, args) MOS_LOG_STREAM_COND(cond, ::mos::console::levels::Warn, MOSCONSOLE_DEFAULT_NAME, args)
#define MOS_WARN_COND_NAMED(cond, name, ...) MOS_LOG_COND(cond, ::mos::console::levels::Warn, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, __VA_ARGS__)
#define MOS_WARN_STREAM_COND_NAMED(cond, name, args) MOS_LOG_STREAM_COND(cond, ::mos::console::levels::Warn, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, args)
#define MOS_WARN_ONCE(...) MOS_LOG_ONCE(::mos::console::levels::Warn, MOSCONSOLE_DEFAULT_NAME, __VA_ARGS__)
#define MOS_WARN_STREAM_ONCE(args) MOS_LOG_STREAM_ONCE(::mos::console::levels::Warn, MOSCONSOLE_DEFAULT_NAME, args)
#define MOS_WARN_ONCE_NAMED(name, ...) MOS_LOG_ONCE(::mos::console::levels::Warn, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, __VA_ARGS__)
#define MOS_WARN_STREAM_ONCE_NAMED(name, args) MOS_LOG_STREAM_ONCE(::mos::console::levels::Warn, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, args)
#define MOS_WARN_THROTTLE(period, ...) MOS_LOG_THROTTLE(period, ::mos::console::levels::Warn, MOSCONSOLE_DEFAULT_NAME, __VA_ARGS__)
#define MOS_WARN_STREAM_THROTTLE(period, args) MOS_LOG_STREAM_THROTTLE(period, ::mos::console::levels::Warn, MOSCONSOLE_DEFAULT_NAME, args)
#define MOS_WARN_THROTTLE_NAMED(period, name, ...) MOS_LOG_THROTTLE(period, ::mos::console::levels::Warn, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, __VA_ARGS__)
#define MOS_WARN_STREAM_THROTTLE_NAMED(period, name, args) MOS_LOG_STREAM_THROTTLE(period, ::mos::console::levels::Warn, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, args)
#define MOS_WARN_DELAYED_THROTTLE(period, ...) MOS_LOG_DELAYED_THROTTLE(period, ::mos::console::levels::Warn, MOSCONSOLE_DEFAULT_NAME, __VA_ARGS__)
#define MOS_WARN_STREAM_DELAYED_THROTTLE(period, args) MOS_LOG_STREAM_DELAYED_THROTTLE(period, ::mos::console::levels::Warn, MOSCONSOLE_DEFAULT_NAME, args)
#define MOS_WARN_DELAYED_THROTTLE_NAMED(period, name, ...) MOS_LOG_DELAYED_THROTTLE(period, ::mos::console::levels::Warn, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, __VA_ARGS__)
#define MOS_WARN_STREAM_DELAYED_THROTTLE_NAMED(period, name, args) MOS_LOG_STREAM_DELAYED_THROTTLE(period, ::mos::console::levels::Warn, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, args)
#define MOS_WARN_FILTER(filter, ...) MOS_LOG_FILTER(filter, ::mos::console::levels::Warn, MOSCONSOLE_DEFAULT_NAME, __VA_ARGS__)
#define MOS_WARN_STREAM_FILTER(filter, args) MOS_LOG_STREAM_FILTER(filter, ::mos::console::levels::Warn, MOSCONSOLE_DEFAULT_NAME, args)
#define MOS_WARN_FILTER_NAMED(filter, name, ...) MOS_LOG_FILTER(filter, ::mos::console::levels::Warn, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, __VA_ARGS__)
#define MOS_WARN_STREAM_FILTER_NAMED(filter, name, args) MOS_LOG_STREAM_FILTER(filter, ::mos::console::levels::Warn, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, args)
#endif

#if (MOSCONSOLE_MIN_SEVERITY > MOSCONSOLE_SEVERITY_ERROR)
#define MOS_ERROR(...)
#define MOS_ERROR_STREAM(args)
#define MOS_ERROR_NAMED(name, ...)
#define MOS_ERROR_STREAM_NAMED(name, args)
#define MOS_ERROR_COND(cond, ...)
#define MOS_ERROR_STREAM_COND(cond, args)
#define MOS_ERROR_COND_NAMED(cond, name, ...)
#define MOS_ERROR_STREAM_COND_NAMED(cond, name, args)
#define MOS_ERROR_ONCE(...)
#define MOS_ERROR_STREAM_ONCE(args)
#define MOS_ERROR_ONCE_NAMED(name, ...)
#define MOS_ERROR_STREAM_ONCE_NAMED(name, args)
#define MOS_ERROR_THROTTLE(period, ...)
#define MOS_ERROR_STREAM_THROTTLE(period, args)
#define MOS_ERROR_THROTTLE_NAMED(period, name, ...)
#define MOS_ERROR_STREAM_THROTTLE_NAMED(period, name, args)
#define MOS_ERROR_DELAYED_THROTTLE(period, ...)
#define MOS_ERROR_STREAM_DELAYED_THROTTLE(period, args)
#define MOS_ERROR_DELAYED_THROTTLE_NAMED(period, name, ...)
#define MOS_ERROR_STREAM_DELAYED_THROTTLE_NAMED(period, name, args)
#define MOS_ERROR_FILTER(filter, ...)
#define MOS_ERROR_STREAM_FILTER(filter, args)
#define MOS_ERROR_FILTER_NAMED(filter, name, ...)
#define MOS_ERROR_STREAM_FILTER_NAMED(filter, name, args)
#else
#define MOS_ERROR(...) MOS_LOG(::mos::console::levels::Error, MOSCONSOLE_DEFAULT_NAME, __VA_ARGS__)
#define MOS_ERROR_STREAM(args) MOS_LOG_STREAM(::mos::console::levels::Error, MOSCONSOLE_DEFAULT_NAME, args)
#define MOS_ERROR_NAMED(name, ...) MOS_LOG(::mos::console::levels::Error, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, __VA_ARGS__)
#define MOS_ERROR_STREAM_NAMED(name, args) MOS_LOG_STREAM(::mos::console::levels::Error, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, args)
#define MOS_ERROR_COND(cond, ...) MOS_LOG_COND(cond, ::mos::console::levels::Error, MOSCONSOLE_DEFAULT_NAME, __VA_ARGS__)
#define MOS_ERROR_STREAM_COND(cond, args) MOS_LOG_STREAM_COND(cond, ::mos::console::levels::Error, MOSCONSOLE_DEFAULT_NAME, args)
#define MOS_ERROR_COND_NAMED(cond, name, ...) MOS_LOG_COND(cond, ::mos::console::levels::Error, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, __VA_ARGS__)
#define MOS_ERROR_STREAM_COND_NAMED(cond, name, args) MOS_LOG_STREAM_COND(cond, ::mos::console::levels::Error, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, args)
#define MOS_ERROR_ONCE(...) MOS_LOG_ONCE(::mos::console::levels::Error, MOSCONSOLE_DEFAULT_NAME, __VA_ARGS__)
#define MOS_ERROR_STREAM_ONCE(args) MOS_LOG_STREAM_ONCE(::mos::console::levels::Error, MOSCONSOLE_DEFAULT_NAME, args)
#define MOS_ERROR_ONCE_NAMED(name, ...) MOS_LOG_ONCE(::mos::console::levels::Error, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, __VA_ARGS__)
#define MOS_ERROR_STREAM_ONCE_NAMED(name, args) MOS_LOG_STREAM_ONCE(::mos::console::levels::Error, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, args)
#define MOS_ERROR_THROTTLE(period, ...) MOS_LOG_THROTTLE(period, ::mos::console::levels::Error, MOSCONSOLE_DEFAULT_NAME, __VA_ARGS__)
#define MOS_ERROR_STREAM_THROTTLE(period, args) MOS_LOG_STREAM_THROTTLE(period, ::mos::console::levels::Error, MOSCONSOLE_DEFAULT_NAME, args)
#define MOS_ERROR_THROTTLE_NAMED(period, name, ...) MOS_LOG_THROTTLE(period, ::mos::console::levels::Error, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, __VA_ARGS__)
#define MOS_ERROR_STREAM_THROTTLE_NAMED(period, name, args) MOS_LOG_STREAM_THROTTLE(period, ::mos::console::levels::Error, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, args)
#define MOS_ERROR_DELAYED_THROTTLE(period, ...) MOS_LOG_DELAYED_THROTTLE(period, ::mos::console::levels::Error, MOSCONSOLE_DEFAULT_NAME, __VA_ARGS__)
#define MOS_ERROR_STREAM_DELAYED_THROTTLE(period, args) MOS_LOG_STREAM_DELAYED_THROTTLE(period, ::mos::console::levels::Error, MOSCONSOLE_DEFAULT_NAME, args)
#define MOS_ERROR_DELAYED_THROTTLE_NAMED(period, name, ...) MOS_LOG_DELAYED_THROTTLE(period, ::mos::console::levels::Error, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, __VA_ARGS__)
#define MOS_ERROR_STREAM_DELAYED_THROTTLE_NAMED(period, name, args) MOS_LOG_STREAM_DELAYED_THROTTLE(period, ::mos::console::levels::Error, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, args)
#define MOS_ERROR_FILTER(filter, ...) MOS_LOG_FILTER(filter, ::mos::console::levels::Error, MOSCONSOLE_DEFAULT_NAME, __VA_ARGS__)
#define MOS_ERROR_STREAM_FILTER(filter, args) MOS_LOG_STREAM_FILTER(filter, ::mos::console::levels::Error, MOSCONSOLE_DEFAULT_NAME, args)
#define MOS_ERROR_FILTER_NAMED(filter, name, ...) MOS_LOG_FILTER(filter, ::mos::console::levels::Error, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, __VA_ARGS__)
#define MOS_ERROR_STREAM_FILTER_NAMED(filter, name, args) MOS_LOG_STREAM_FILTER(filter, ::mos::console::levels::Error, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, args)
#endif

#if (MOSCONSOLE_MIN_SEVERITY > MOSCONSOLE_SEVERITY_FATAL)
#define MOS_FATAL(...)
#define MOS_FATAL_STREAM(args)
#define MOS_FATAL_NAMED(name, ...)
#define MOS_FATAL_STREAM_NAMED(name, args)
#define MOS_FATAL_COND(cond, ...)
#define MOS_FATAL_STREAM_COND(cond, args)
#define MOS_FATAL_COND_NAMED(cond, name, ...)
#define MOS_FATAL_STREAM_COND_NAMED(cond, name, args)
#define MOS_FATAL_ONCE(...)
#define MOS_FATAL_STREAM_ONCE(args)
#define MOS_FATAL_ONCE_NAMED(name, ...)
#define MOS_FATAL_STREAM_ONCE_NAMED(name, args)
#define MOS_FATAL_THROTTLE(period, ...)
#define MOS_FATAL_STREAM_THROTTLE(period, args)
#define MOS_FATAL_THROTTLE_NAMED(period, name, ...)
#define MOS_FATAL_STREAM_THROTTLE_NAMED(period, name, args)
#define MOS_FATAL_DELAYED_THROTTLE(period, ...)
#define MOS_FATAL_STREAM_DELAYED_THROTTLE(period, args)
#define MOS_FATAL_DELAYED_THROTTLE_NAMED(period, name, ...)
#define MOS_FATAL_STREAM_DELAYED_THROTTLE_NAMED(period, name, args)
#define MOS_FATAL_FILTER(filter, ...)
#define MOS_FATAL_STREAM_FILTER(filter, args)
#define MOS_FATAL_FILTER_NAMED(filter, name, ...)
#define MOS_FATAL_STREAM_FILTER_NAMED(filter, name, args)
#else
#define MOS_FATAL(...) MOS_LOG(::mos::console::levels::Fatal, MOSCONSOLE_DEFAULT_NAME, __VA_ARGS__)
#define MOS_FATAL_STREAM(args) MOS_LOG_STREAM(::mos::console::levels::Fatal, MOSCONSOLE_DEFAULT_NAME, args)
#define MOS_FATAL_NAMED(name, ...) MOS_LOG(::mos::console::levels::Fatal, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, __VA_ARGS__)
#define MOS_FATAL_STREAM_NAMED(name, args) MOS_LOG_STREAM(::mos::console::levels::Fatal, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, args)
#define MOS_FATAL_COND(cond, ...) MOS_LOG_COND(cond, ::mos::console::levels::Fatal, MOSCONSOLE_DEFAULT_NAME, __VA_ARGS__)
#define MOS_FATAL_STREAM_COND(cond, args) MOS_LOG_STREAM_COND(cond, ::mos::console::levels::Fatal, MOSCONSOLE_DEFAULT_NAME, args)
#define MOS_FATAL_COND_NAMED(cond, name, ...) MOS_LOG_COND(cond, ::mos::console::levels::Fatal, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, __VA_ARGS__)
#define MOS_FATAL_STREAM_COND_NAMED(cond, name, args) MOS_LOG_STREAM_COND(cond, ::mos::console::levels::Fatal, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, args)
#define MOS_FATAL_ONCE(...) MOS_LOG_ONCE(::mos::console::levels::Fatal, MOSCONSOLE_DEFAULT_NAME, __VA_ARGS__)
#define MOS_FATAL_STREAM_ONCE(args) MOS_LOG_STREAM_ONCE(::mos::console::levels::Fatal, MOSCONSOLE_DEFAULT_NAME, args)
#define MOS_FATAL_ONCE_NAMED(name, ...) MOS_LOG_ONCE(::mos::console::levels::Fatal, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, __VA_ARGS__)
#define MOS_FATAL_STREAM_ONCE_NAMED(name, args) MOS_LOG_STREAM_ONCE(::mos::console::levels::Fatal, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, args)
#define MOS_FATAL_THROTTLE(period, ...) MOS_LOG_THROTTLE(period, ::mos::console::levels::Fatal, MOSCONSOLE_DEFAULT_NAME, __VA_ARGS__)
#define MOS_FATAL_STREAM_THROTTLE(period, args) MOS_LOG_STREAM_THROTTLE(period, ::mos::console::levels::Fatal, MOSCONSOLE_DEFAULT_NAME, args)
#define MOS_FATAL_THROTTLE_NAMED(period, name, ...) MOS_LOG_THROTTLE(period, ::mos::console::levels::Fatal, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, __VA_ARGS__)
#define MOS_FATAL_STREAM_THROTTLE_NAMED(period, name, args) MOS_LOG_STREAM_THROTTLE(period, ::mos::console::levels::Fatal, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, args)
#define MOS_FATAL_DELAYED_THROTTLE(period, ...) MOS_LOG_DELAYED_THROTTLE(period, ::mos::console::levels::Fatal, MOSCONSOLE_DEFAULT_NAME, __VA_ARGS__)
#define MOS_FATAL_STREAM_DELAYED_THROTTLE(period, args) MOS_LOG_STREAM_DELAYED_THROTTLE(period, ::mos::console::levels::Fatal, MOSCONSOLE_DEFAULT_NAME, args)
#define MOS_FATAL_DELAYED_THROTTLE_NAMED(period, name, ...) MOS_LOG_DELAYED_THROTTLE(period, ::mos::console::levels::Fatal, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, __VA_ARGS__)
#define MOS_FATAL_STREAM_DELAYED_THROTTLE_NAMED(period, name, args) MOS_LOG_STREAM_DELAYED_THROTTLE(period, ::mos::console::levels::Fatal, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, args)
#define MOS_FATAL_FILTER(filter, ...) MOS_LOG_FILTER(filter, ::mos::console::levels::Fatal, MOSCONSOLE_DEFAULT_NAME, __VA_ARGS__)
#define MOS_FATAL_STREAM_FILTER(filter, args) MOS_LOG_STREAM_FILTER(filter, ::mos::console::levels::Fatal, MOSCONSOLE_DEFAULT_NAME, args)
#define MOS_FATAL_FILTER_NAMED(filter, name, ...) MOS_LOG_FILTER(filter, ::mos::console::levels::Fatal, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, __VA_ARGS__)
#define MOS_FATAL_STREAM_FILTER_NAMED(filter, name, args) MOS_LOG_STREAM_FILTER(filter, ::mos::console::levels::Fatal, std::string(MOSCONSOLE_NAME_PREFIX) + "." + name, args)
#endif

