TEMPLATE = app
CONFIG += console c++14
CONFIG -= app_bundle
QT += widgets

INCLUDEPATH += ../src
INCLUDEPATH += ../src/rviz
INCLUDEPATH += ../src/utils
INCLUDEPATH += /usr/include/OGRE
INCLUDEPATH += /usr/include/eigen3
INCLUDEPATH += /usr/include/python3.8

LIBS += -ltinyxml -ltinyxml2
LIBS += -lcurl -lpython3.8 -lX11
LIBS += -lassimp -lyaml-cpp -lzzip
LIBS += -lfreeimage -ljpegxr -ljxrglue
LIBS += -lconsole_bridge -lPocoFoundation
LIBS += -lOgreOverlay -lOgreMain -lOgreProperty
LIBS += -lboost_filesystem -lboost_program_options
LIBS += -lboost_chrono -lboost_regex -lboost_thread

SOURCES +=  ../src/rviz/main.cpp \
    \
    ../src/rviz/add_display_dialog.cpp \
    ../src/rviz/bit_allocator.cpp \
    ../src/rviz/config.cpp \
    ../src/rviz/default_plugin/grid_display.cpp \
    ../src/rviz/default_plugin/tools/focus_tool.cpp \
    ../src/rviz/default_plugin/tools/goal_tool.cpp \
    ../src/rviz/default_plugin/tools/initial_pose_tool.cpp \
    ../src/rviz/default_plugin/tools/interaction_tool.cpp \
    ../src/rviz/default_plugin/tools/measure_tool.cpp \
    ../src/rviz/default_plugin/tools/move_tool.cpp \
    ../src/rviz/default_plugin/tools/point_tool.cpp \
    ../src/rviz/default_plugin/tools/pose_tool.cpp \
    ../src/rviz/default_plugin/tools/selection_tool.cpp \
    ../src/rviz/default_plugin/view_controllers/fixed_orientation_ortho_view_controller.cpp \
    ../src/rviz/default_plugin/view_controllers/fps_view_controller.cpp \
    ../src/rviz/default_plugin/view_controllers/frame_view_controller.cpp \
    ../src/rviz/default_plugin/view_controllers/orbit_view_controller.cpp \
    ../src/rviz/default_plugin/view_controllers/third_person_follower_view_controller.cpp \
    ../src/rviz/default_plugin/view_controllers/xy_orbit_view_controller.cpp \
    ../src/rviz/display.cpp \
    ../src/rviz/display_factory.cpp \
    ../src/rviz/display_group.cpp \
    ../src/rviz/displays_panel.cpp \
    ../src/rviz/env_config.cpp \
    ../src/rviz/failed_display.cpp \
    ../src/rviz/failed_panel.cpp \
    ../src/rviz/failed_tool.cpp \
    ../src/rviz/failed_view_controller.cpp \
    ../src/rviz/frame_manager.cpp \
    ../src/rviz/frame_position_tracking_view_controller.cpp \
    ../src/rviz/geometry.cpp \
    ../src/rviz/help_panel.cpp \
    ../src/rviz/image/image_display_base.cpp \
    ../src/rviz/load_resource.cpp \
    ../src/rviz/loading_dialog.cpp \
    ../src/rviz/mesh_loader.cpp \
    ../src/rviz/new_object_dialog.cpp \
    ../src/rviz/ogre_helpers/apply_visibility_bits.cpp \
    ../src/rviz/ogre_helpers/arrow.cpp \
    ../src/rviz/ogre_helpers/axes.cpp \
    ../src/rviz/ogre_helpers/billboard_line.cpp \
    ../src/rviz/ogre_helpers/camera_base.cpp \
    ../src/rviz/ogre_helpers/grid.cpp \
    ../src/rviz/ogre_helpers/initialization.cpp \
    ../src/rviz/ogre_helpers/line.cpp \
    ../src/rviz/ogre_helpers/mesh_shape.cpp \
    ../src/rviz/ogre_helpers/movable_text.cpp \
    ../src/rviz/ogre_helpers/object.cpp \
    ../src/rviz/ogre_helpers/ogre_logging.cpp \
    ../src/rviz/ogre_helpers/ogre_render_queue_clearer.cpp \
    ../src/rviz/ogre_helpers/orbit_camera.cpp \
    ../src/rviz/ogre_helpers/orthographic.cpp \
    ../src/rviz/ogre_helpers/point_cloud.cpp \
    ../src/rviz/ogre_helpers/qt_ogre_render_window.cpp \
    ../src/rviz/ogre_helpers/render_system.cpp \
    ../src/rviz/ogre_helpers/render_widget.cpp \
    ../src/rviz/ogre_helpers/shape.cpp \
    ../src/rviz/panel.cpp \
    ../src/rviz/panel_dock_widget.cpp \
    ../src/rviz/panel_factory.cpp \
    ../src/rviz/preferences_dialog.cpp \
    ../src/rviz/properties/bool_property.cpp \
    ../src/rviz/properties/color_editor.cpp \
    ../src/rviz/properties/color_property.cpp \
    ../src/rviz/properties/combo_box.cpp \
    ../src/rviz/properties/display_group_visibility_property.cpp \
    ../src/rviz/properties/display_visibility_property.cpp \
    ../src/rviz/properties/editable_combo_box.cpp \
    ../src/rviz/properties/editable_enum_property.cpp \
    ../src/rviz/properties/enum_property.cpp \
    ../src/rviz/properties/float_edit.cpp \
    ../src/rviz/properties/float_property.cpp \
    ../src/rviz/properties/int_property.cpp \
    ../src/rviz/properties/line_edit_with_button.cpp \
    ../src/rviz/properties/mos_topic_property.cpp \
    ../src/rviz/properties/parse_color.cpp \
    ../src/rviz/properties/property.cpp \
    ../src/rviz/properties/property_tree_delegate.cpp \
    ../src/rviz/properties/property_tree_model.cpp \
    ../src/rviz/properties/property_tree_widget.cpp \
    ../src/rviz/properties/property_tree_with_help.cpp \
    ../src/rviz/properties/quaternion_property.cpp \
    ../src/rviz/properties/splitter_handle.cpp \
    ../src/rviz/properties/status_list.cpp \
    ../src/rviz/properties/status_property.cpp \
    ../src/rviz/properties/string_property.cpp \
    ../src/rviz/properties/tf_frame_property.cpp \
    ../src/rviz/properties/vector_property.cpp \
    ../src/rviz/render_panel.cpp \
    ../src/rviz/robot/robot.cpp \
    ../src/rviz/robot/robot_joint.cpp \
    ../src/rviz/robot/robot_link.cpp \
    ../src/rviz/robot/tf_link_updater.cpp \
    ../src/rviz/scaled_image_widget.cpp \
    ../src/rviz/screenshot_dialog.cpp \
    ../src/rviz/selection/selection_handler.cpp \
    ../src/rviz/selection/selection_manager.cpp \
    ../src/rviz/selection_panel.cpp \
    ../src/rviz/splash_screen.cpp \
    ../src/rviz/time_panel.cpp \
    ../src/rviz/tool.cpp \
    ../src/rviz/tool_manager.cpp \
    ../src/rviz/tool_properties_panel.cpp \
    ../src/rviz/uniform_string_stream.cpp \
    ../src/rviz/view_controller.cpp \
    ../src/rviz/view_manager.cpp \
    ../src/rviz/views_panel.cpp \
    ../src/rviz/visualization_frame.cpp \
    ../src/rviz/visualization_manager.cpp \
    ../src/rviz/visualizer_app.cpp \
    ../src/rviz/widget_geometry_change_detector.cpp \
    ../src/rviz/yaml_config_reader.cpp \
    ../src/rviz/yaml_config_writer.cpp \
    ../src/utils/impl/mos_console_print.cpp \
    ../src/utils/libmos/callback_queue.cpp \
    ../src/utils/libmos/common.cpp \
    ../src/utils/libmos/connection.cpp \
    ../src/utils/libmos/connection_manager.cpp \
    ../src/utils/libmos/file_log.cpp \
    ../src/utils/libmos/init.cpp \
    ../src/utils/libmos/internal_timer_manager.cpp \
    ../src/utils/libmos/intraprocess_publisher_link.cpp \
    ../src/utils/libmos/intraprocess_subscriber_link.cpp \
    ../src/utils/libmos/io.cpp \
    ../src/utils/libmos/master.cpp \
    ../src/utils/libmos/message_deserializer.cpp \
    ../src/utils/libmos/mosout_appender.cpp \
    ../src/utils/libmos/names.cpp \
    ../src/utils/libmos/network.cpp \
    ../src/utils/libmos/node_handle.cpp \
    ../src/utils/libmos/param.cpp \
    ../src/utils/libmos/poll_manager.cpp \
    ../src/utils/libmos/poll_set.cpp \
    ../src/utils/libmos/publication.cpp \
    ../src/utils/libmos/publisher.cpp \
    ../src/utils/libmos/publisher_link.cpp \
    ../src/utils/libmos/service.cpp \
    ../src/utils/libmos/service_client.cpp \
    ../src/utils/libmos/service_client_link.cpp \
    ../src/utils/libmos/service_manager.cpp \
    ../src/utils/libmos/service_publication.cpp \
    ../src/utils/libmos/service_server.cpp \
    ../src/utils/libmos/service_server_link.cpp \
    ../src/utils/libmos/single_subscriber_publisher.cpp \
    ../src/utils/libmos/spinner.cpp \
    ../src/utils/libmos/statistics.cpp \
    ../src/utils/libmos/steady_timer.cpp \
    ../src/utils/libmos/subscriber.cpp \
    ../src/utils/libmos/subscriber_link.cpp \
    ../src/utils/libmos/subscription.cpp \
    ../src/utils/libmos/subscription_queue.cpp \
    ../src/utils/libmos/this_node.cpp \
    ../src/utils/libmos/timer.cpp \
    ../src/utils/libmos/topic_manager.cpp \
    ../src/utils/libmos/transport_publisher_link.cpp \
    ../src/utils/libmos/transport_subscriber_link.cpp \
    ../src/utils/libmos/transport_udp.cpp \
    ../src/utils/libmos/wall_timer.cpp \
    ../src/utils/libmos/xmlrpc_manager.cpp \
    ../src/utils/mos_class_loader/class_loader.cpp \
    ../src/utils/mos_class_loader/class_loader_core.cpp \
    ../src/utils/mos_class_loader/meta_object.cpp \
    ../src/utils/mos_class_loader/multi_library_class_loader.cpp \
    ../src/utils/mos_class_loader/multi_library_class_loader.hpp \
    ../src/utils/mos_common_debug.cpp \
    ../src/utils/mos_common_header.cpp \
    ../src/utils/mos_console.cpp \
    ../src/utils/mos_console_backend.cpp \
    ../src/utils/mos_console_bridge/bridge.cpp \
    ../src/utils/mos_image_transport/camera_common.cpp \
    ../src/utils/mos_image_transport/camera_publisher.cpp \
    ../src/utils/mos_image_transport/camera_subscriber.cpp \
    ../src/utils/mos_image_transport/image_publisher.cpp \
    ../src/utils/mos_image_transport/image_single_subscriber_publisher.cpp \
    ../src/utils/mos_image_transport/image_subscriber.cpp \
    ../src/utils/mos_image_transport/image_transport.cpp \
    ../src/utils/mos_message_filters/msg_connection.cpp \
    ../src/utils/mos_package.cpp \
    ../src/utils/mos_retriever.cpp \
    ../src/utils/mos_serialization.cpp \
    ../src/utils/mos_tf2/buffer.cpp \
    ../src/utils/mos_tf2/buffer_core.cpp \
    ../src/utils/mos_tf2/cache.cpp \
    ../src/utils/mos_tf2/static_cache.cpp \
    ../src/utils/mos_tf2/transform_listener.cpp \
    ../src/utils/mos_time/mos_duration.cpp \
    ../src/utils/mos_time/mos_time.cpp \
    ../src/utils/mos_transport/transport.cpp \
    ../src/utils/mos_transport/transport_tcp.cpp \
    ../src/utils/mospack/mos_pack.cpp \
    ../src/utils/mospack/mospack_backcompat.cpp \
    ../src/utils/mospack/mospack_cmdline.cpp \
    ../src/utils/mospack/mospack_utils.cpp \
    ../src/utils/xmlrpcpp/XmlRpcClient.cpp \
    ../src/utils/xmlrpcpp/XmlRpcDispatch.cpp \
    ../src/utils/xmlrpcpp/XmlRpcServer.cpp \
    ../src/utils/xmlrpcpp/XmlRpcServerConnection.cpp \
    ../src/utils/xmlrpcpp/XmlRpcServerMethod.cpp \
    ../src/utils/xmlrpcpp/XmlRpcSocket.cpp \
    ../src/utils/xmlrpcpp/XmlRpcSource.cpp \
    ../src/utils/xmlrpcpp/XmlRpcUtil.cpp \
    ../src/utils/xmlrpcpp/XmlRpcValue.cpp \
    ../src/utils/xmlrpcpp/cdecode.c \
    ../src/utils/xmlrpcpp/cencode.c \

HEADERS += \
    ../src/rviz/add_display_dialog.h \
    ../src/rviz/default_plugin/grid_display.h \
    ../src/rviz/default_plugin/tools/focus_tool.h \
    ../src/rviz/default_plugin/tools/goal_tool.h \
    ../src/rviz/default_plugin/tools/initial_pose_tool.h \
    ../src/rviz/default_plugin/tools/interaction_tool.h \
    ../src/rviz/default_plugin/tools/measure_tool.h \
    ../src/rviz/default_plugin/tools/move_tool.h \
    ../src/rviz/default_plugin/tools/point_tool.h \
    ../src/rviz/default_plugin/tools/pose_tool.h \
    ../src/rviz/default_plugin/tools/selection_tool.h \
    ../src/rviz/default_plugin/view_controllers/fixed_orientation_ortho_view_controller.h \
    ../src/rviz/default_plugin/view_controllers/fps_view_controller.h \
    ../src/rviz/default_plugin/view_controllers/frame_view_controller.h \
    ../src/rviz/default_plugin/view_controllers/orbit_view_controller.h \
    ../src/rviz/default_plugin/view_controllers/third_person_follower_view_controller.h \
    ../src/rviz/default_plugin/view_controllers/xy_orbit_view_controller.h \
    ../src/rviz/display.h \
    ../src/rviz/display_context.h \
    ../src/rviz/display_group.h \
    ../src/rviz/displays_panel.h \
    ../src/rviz/failed_panel.h \
    ../src/rviz/frame_manager.h \
    ../src/rviz/frame_position_tracking_view_controller.h \
    ../src/rviz/help_panel.h \
    ../src/rviz/image/image_display_base.h \
    ../src/rviz/loading_dialog.h \
    ../src/rviz/new_object_dialog.h \
    ../src/rviz/ogre_helpers/apply_visibility_bits.h \
    ../src/rviz/ogre_helpers/arrow.h \
    ../src/rviz/ogre_helpers/axes.h \
    ../src/rviz/ogre_helpers/billboard_line.h \
    ../src/rviz/ogre_helpers/camera_base.h \
    ../src/rviz/ogre_helpers/grid.h \
    ../src/rviz/ogre_helpers/initialization.h \
    ../src/rviz/ogre_helpers/line.h \
    ../src/rviz/ogre_helpers/mesh_shape.h \
    ../src/rviz/ogre_helpers/movable_text.h \
    ../src/rviz/ogre_helpers/object.h \
    ../src/rviz/ogre_helpers/ogre_logging.h \
    ../src/rviz/ogre_helpers/ogre_render_queue_clearer.h \
    ../src/rviz/ogre_helpers/orbit_camera.h \
    ../src/rviz/ogre_helpers/orthographic.h \
    ../src/rviz/ogre_helpers/point_cloud.h \
    ../src/rviz/ogre_helpers/qt_ogre_render_window.h \
    ../src/rviz/ogre_helpers/render_system.h \
    ../src/rviz/ogre_helpers/render_widget.h \
    ../src/rviz/ogre_helpers/shape.h \
    ../src/rviz/panel.h \
    ../src/rviz/panel_dock_widget.h \
    ../src/rviz/preferences_dialog.h \
    ../src/rviz/properties/bool_property.h \
    ../src/rviz/properties/color_editor.h \
    ../src/rviz/properties/color_property.h \
    ../src/rviz/properties/combo_box.h \
    ../src/rviz/properties/display_group_visibility_property.h \
    ../src/rviz/properties/display_visibility_property.h \
    ../src/rviz/properties/editable_combo_box.h \
    ../src/rviz/properties/editable_enum_property.h \
    ../src/rviz/properties/enum_property.h \
    ../src/rviz/properties/float_edit.h \
    ../src/rviz/properties/float_property.h \
    ../src/rviz/properties/int_property.h \
    ../src/rviz/properties/line_edit_with_button.h \
    ../src/rviz/properties/mos_topic_property.h \
    ../src/rviz/properties/parse_color.h \
    ../src/rviz/properties/property.h \
    ../src/rviz/properties/property_tree_delegate.h \
    ../src/rviz/properties/property_tree_model.h \
    ../src/rviz/properties/property_tree_widget.h \
    ../src/rviz/properties/property_tree_with_help.h \
    ../src/rviz/properties/quaternion_property.h \
    ../src/rviz/properties/splitter_handle.h \
    ../src/rviz/properties/status_list.h \
    ../src/rviz/properties/status_property.h \
    ../src/rviz/properties/string_property.h \
    ../src/rviz/properties/tf_frame_property.h \
    ../src/rviz/properties/vector_property.h \
    ../src/rviz/render_panel.h \
    ../src/rviz/robot/robot.h \
    ../src/rviz/robot/robot_joint.h \
    ../src/rviz/robot/robot_link.h \
    ../src/rviz/scaled_image_widget.h \
    ../src/rviz/screenshot_dialog.h \
    ../src/rviz/selection/selection_manager.h \
    ../src/rviz/selection_panel.h \
    ../src/rviz/splash_screen.h \
    ../src/rviz/time_panel.h \
    ../src/rviz/tool.h \
    ../src/rviz/tool_manager.h \
    ../src/rviz/tool_properties_panel.h \
    ../src/rviz/view_controller.h \
    ../src/rviz/view_manager.h \
    ../src/rviz/views_panel.h \
    ../src/rviz/visualization_frame.h \
    ../src/rviz/visualization_manager.h \
    ../src/rviz/visualizer_app.h \
    ../src/rviz/widget_geometry_change_detector.h \
